language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
install: npm install
script:
  - npm run test
  - bash ./docs/deploy/deploy.sh
env:
  global:
    - ENCRYPTION_LABEL: "be0b3b658a36"
    - COMMIT_AUTHOR_EMAIL: "blactbt@live.de"
    - CXX=g++-4.9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
